### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by adlbrtbsr** [LissaGreense/water-movie-melon#52]
### Description
README file hasn't been updated in a long time, it's short and provides very low info on this project.

### Before you start

- think about longer, more descriptive info on how the project works
- consider adding some graphics

### To complete this task
- update the README file
- Describe the structure of the project
- Add badges for github actions

For every service:
- List the requirements and describe how to install them
- How to run unittests
- Describe the .env file and and variables it contains

**Comment by LissaGreense** [comment]
From my perspective we should add:

- Describe structure of the project (we have a monorepo for two services, so it should be noted)
- Badges for our github actions
- Describe running with docker-compose
- Contribution guideline (optional)

For every service:
- Requirements (what is needed to start working with project) and how to install them (commands)
- How to run unittests (I know we don't have a lot of them, but I think it should be here anyway)
- Describe required .env files and describe variables it contain
- Run app as a container (how to run docker, link to docker site how to setup it)

I don't like point "consider listing technologies and their versions used in this project". For my perspective it's not needed. We have

**Comment by LissaGreense** [comment]
Docker files and docker-compose should be validated first. Moved to another task.

**Comment by LissaGreense** [comment]
Thank you for updating the task :)

**Comment by LissaGreense** [comment]
I will skip badges part because we have to first create actions for units and fix build actions~
